name: Tauri

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: tauri-apps/tauri-action@v0
    - uses: actions/checkout@v3
    - run: npm install
    - name: Build
      run: npm run tauri dev
    - name: Run tests
      run: cargo test --verbose
